services:
  - type: web
    name: back
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/main.py
  - type: web
    name: front
    env: static
    rootDir: frontend
    buildCommand: yarn build
    staticPublishPath: ./build